---
- name: Prepare windows image for OpenShift
  hosts: localhost

  tasks:

    - name: Create Temp Build Directory
      tempfile:
        state: directory
        suffix: win-image
      register: win_image_tempdir

    - name: "Create scripts dir ..."
      file:
        path: "{{ win_image_tempdir.path }}/scripts"
        state: directory
        mode: '0755'

    - name: "Generating build.json file ..."
      template:
        src: build.json.j2
        dest: "{{ win_image_tempdir.path }}/build.json"

    - name: "Generating authorized_keys file ..."
      copy:
        content: "{{ ssh_pub_key }}"
        dest: "{{ win_image_tempdir.path }}/scripts/authorized_keys"

    - name: "Generating autounattend.xml file ..."
      template:
        src: autounattend.xml.j2
        dest: "{{ win_image_tempdir.path }}/scripts/autounattend.xml"

    - name: "Copying powershell scripts ..."
      copy:
        src: "{{ item }}"
        dest: "{{ win_image_tempdir.path }}/scripts/{{ item }}"
      loop:
        - install-docker.ps1
        - install-vm-tools.cmd
        - win-updates.ps1
        - powershell.ps1

    - name: "Downloading packer ..."
      get_url:
        url: "{{ download.packer }}"
        dest: "{{ win_image_tempdir.path }}/packer.zip"
        mode: '0755'

    - name: "Unzip packer ..."
      unarchive:
        src: "{{ win_image_tempdir.path }}/packer.zip"
        dest: "{{ win_image_tempdir.path }}/"

    - name: "Running packer ... This may take up to 30 minutes! For more details check the log file in: {{ win_image_tempdir.path }}"
      shell:
        cmd: "PACKER_LOG=1 {{ win_image_tempdir.path }}/packer build -force build.json > {{ win_image_tempdir.path }}/output-{{ ansible_date_time.iso8601_basic_short }}.log 2>&1"
        chdir: "{{ win_image_tempdir.path }}/"
